name-template: 'Draft for v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'

categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'Type: Enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: 'ğŸ§° Maintenance'
    label: 'Type: Maintenance'

change-template: '- #$NUMBER $TITLE (@$AUTHOR)'

exclude-labels:
  - 'Topic: CI/CD'

template: |
  ## Changes

  $CHANGES
